<?php

/**
 * Static site generator for the GitHub Pages docs.
 *
 * Renders docs/page.php to _site/index.html with every showcase avatar
 * pre-rendered by the real PHP renderer, and exports the package's face data,
 * sphere positions, palette and defaults to _site/assets/facehash-data.js so the
 * browser playground renders arbitrary names from the same source of truth.
 *
 *   php docs/build.php            # build into _site/
 *   php -S localhost:8080 -t _site
 */

declare(strict_types=1);

$root = dirname(__DIR__);

require_once $root . '/src/Enums/FaceType.php';
require_once $root . '/src/Enums/Format.php';
require_once $root . '/src/Enums/Variant.php';
require_once $root . '/src/Data/FacehashData.php';
require_once $root . '/src/Data/FaceSvgData.php';
require_once $root . '/src/Support/SvgRenderer.php';
require_once $root . '/src/Facehash.php';

use Saade\Facehash\Data\FaceSvgData;
use Saade\Facehash\Enums\FaceType;
use Saade\Facehash\Enums\Format;
use Saade\Facehash\Enums\Variant;
use Saade\Facehash\Facehash;

$out = $root . '/_site';

// The canonical origin. Drives the absolute URLs in the page metadata and the
// CNAME file GitHub Pages needs to serve (and issue a certificate for) the
// custom domain.
$siteUrl = 'https://facehash.saade.dev';

/**
 * Read the package's shipped defaults out of the class itself, so the docs never
 * state a default the code no longer has.
 */
function packageData(): array
{
    $reflection = new ReflectionClass(Facehash::class);
    $instance = new Facehash;

    $property = static function (string $name) use ($reflection, $instance) {
        $value = $reflection->getProperty($name)->getValue($instance);

        return $value instanceof BackedEnum ? $value->value : $value;
    };

    $faces = [];

    foreach (FaceType::cases() as $faceType) {
        $faces[$faceType->value] = FaceSvgData::get($faceType);
    }

    return [
        'faces' => $faces,
        'faceTypes' => array_map(fn (FaceType $type) => $type->value, FaceType::cases()),
        'spherePositions' => $reflection->getConstant('SPHERE_POSITIONS'),
        'colors' => $property('colorPalette'),
        'defaults' => [
            'size' => $property('size'),
            'variant' => $property('variant'),
            'format' => $property('format'),
            'initial' => $property('showInitial'),
            'blink' => $property('enableBlink'),
        ],
    ];
}

function rmdirRecursive(string $dir): void
{
    if (! is_dir($dir)) {
        return;
    }

    $items = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );

    foreach ($items as $item) {
        $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
    }

    rmdir($dir);
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

rmdirRecursive($out);
mkdir($out . '/assets', 0755, true);

$data = packageData();

// Values the template needs — enum cases drive the showcases so a new face type,
// format or variant shows up in the docs without editing the template.
$facehash = new Facehash;
$formats = array_map(fn (Format $format) => $format->value, Format::cases());
$variants = array_map(fn (Variant $variant) => $variant->value, Variant::cases());
$faceTypes = $data['faceTypes'];
$defaults = $data['defaults'];
$colors = $data['colors'];

ob_start();
require __DIR__ . '/page.php';
file_put_contents($out . '/index.html', ob_get_clean());

file_put_contents(
    $out . '/assets/facehash-data.js',
    "// Generated by docs/build.php — do not edit.\nexport default "
        . json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)
        . ";\n"
);

foreach (glob(__DIR__ . '/assets/*') as $asset) {
    copy($asset, $out . '/assets/' . basename($asset));
}

copy($root . '/art/cover.png', $out . '/assets/cover.png');

// GitHub Pages runs Jekyll by default, which would swallow the assets directory.
touch($out . '/.nojekyll');

// Tells Pages which custom domain this artifact is for. Without it the domain
// setting can be dropped on deploy, which takes the TLS certificate with it.
file_put_contents($out . '/CNAME', parse_url($siteUrl, PHP_URL_HOST) . "\n");

$bytes = filesize($out . '/index.html');
echo "Built _site/index.html (" . number_format($bytes / 1024, 1) . " KB)\n";
